env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Kafka {
    bootstrap.servers = "host.docker.internal:19092"
    topic = "mongo_to_clickhouse"
    consumer.group = "seatunnel_mongo_clickhouse_group_v9"
    format = "json"
    result_table_name = "kafka_stream_data"
    
    schema = {
      fields {
        _id = "string"
        name = "string"
        email = "string"
        age = "int"
        account_balance = "double"
        country = "string"
        is_active_member = "boolean"
        cybernetic_level = "int"
        created_at = "string"
      }
    }
    
    kafka.config = {
      auto.offset.reset = "earliest"
      enable.auto.commit = "true"
    }
  }
}

sink {
  Clickhouse {
    host = "host.docker.internal:8123"
    database = "default"
    table = "users"
    username = "default"
    password = "clickhouse123"
    bulk_size = 500
    source_table_name = "kafka_stream_data"
    clickhouse.config = {
      compress = "0"
    }
  }
}
