name: "pg_to_mysql"
source:
  type: "postgres"
  config:
    host: "localhost"
    port: 5431
    user: "admin"
    password: "password123"
    dbname: "sample_db"
target:
  type: "mysql"
  config:
    host: "localhost"
    port: 3306
    user: "root"
    password: "password123"
    database: "sample_db"
tables:
  - customers
  - orders
